# This file is generated by scripts/update-formula.sh — do not edit by hand.
# To update: make release VERSION=<version>
class Jcli < Formula
  desc "Comprehensive command-line interface for the Jira REST API v2"
  homepage "https://github.com/steveohara/jcli"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.1.0/jcli-v1.1.0-darwin-amd64.tar.gz"
      sha256 "8378eafd1b34d61551efd7a87be6044219b626f71fe5c3a71cd64d4975ac6967"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.1.0/jcli-v1.1.0-darwin-arm64.tar.gz"
      sha256 "301690ad20c443d2c53dbd54b161d65c9fb78197d80cee7b64c71d7262c2471c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.1.0/jcli-v1.1.0-linux-amd64.tar.gz"
      sha256 "d24c1abccc894b2559e65d89c46ec22d810adb228be31755cccf5f3273b8eea0"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.1.0/jcli-v1.1.0-linux-arm64.tar.gz"
      sha256 "c7e514cd57df9ecb0f8725acf01cd3fa6c4b9ef0ff631b7298957549ebfc5d94"
    end
  end

  def install
    bin.install "jcli"
    (share/"jcli").install "SKILL.md"
  end

  def caveats
    <<~EOS
      The Jira agent skill for OpenCode and compatible AI tools has been installed to:
        #{share}/jcli/SKILL.md

      To activate it globally, run:
        mkdir -p ~/.agents/skills/jira
        ln -sf "#{share}/jcli/SKILL.md" ~/.agents/skills/jira/SKILL.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jcli --version")
  end
end
