# This file is generated by scripts/update-formula.sh — do not edit by hand.
# To update: make release VERSION=<version>
class Jcli < Formula
  desc "Comprehensive command-line interface for the Jira REST API v2"
  homepage "https://github.com/steveohara/jcli"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-darwin-amd64.tar.gz"
      sha256 "79c56b41d374bd9854d1866047756c67d7a6c087487afa1ca75bf39f6c8fe5a7"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-darwin-arm64.tar.gz"
      sha256 "5e091c56d150b6d710cee85f7dd5223ce863e59526f652b476a142b1eea39354"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-linux-amd64.tar.gz"
      sha256 "ad61a2d3834d9a41017bd9bdb0f5f34f036468be47e0f25a405beb804ab1bf41"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-linux-arm64.tar.gz"
      sha256 "c2b96ca491f36d5ada9105a41d14e84453fe56f1eb24d617555e76624af5bef3"
    end
  end

  def install
    bin.install "jcli"
    (share/"jcli").install "SKILL.md"
  end

  def caveats
    <<~EOS
      The Jira agent skill for OpenCode and compatible AI tools has been installed to:
        #{share}/jcli/SKILL.md

      To activate it globally, run:
        mkdir -p ~/.agents/skills/jira
        ln -sf "#{share}/jcli/SKILL.md" ~/.agents/skills/jira/SKILL.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jcli --version")
  end
end
