# This file is generated by scripts/update-formula.sh — do not edit by hand.
# To update: make release VERSION=<version>
class Jcli < Formula
  desc "Comprehensive command-line interface for the Jira REST API v2"
  homepage "https://github.com/steveohara/jcli"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-darwin-amd64.tar.gz"
      sha256 "f5842bc86b3dd2f17a019b53f6604567b8e933ea22de2b239d47510028af69af"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-darwin-arm64.tar.gz"
      sha256 "356e0a1421a793190294e313a509b7c2f55e932ad4de283734111684316e0eb0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-linux-amd64.tar.gz"
      sha256 "ef8fcc78bd2aaf9fbac6a00a9196470e0fafa4912273d9573b4b24a70849d1d0"
    end

    on_arm do
      url "https://github.com/steveohara/jcli/releases/download/v1.2.0/jcli-v1.2.0-linux-arm64.tar.gz"
      sha256 "b93713c478559e1cb08750e87ccd03077ebf9d49a8e2e74d8785d5ee76362cb6"
    end
  end

  def install
    bin.install "jcli"
    (share/"jcli").install "SKILL.md"
  end

  def caveats
    <<~EOS
      The Jira agent skill for OpenCode and compatible AI tools has been installed to:
        #{share}/jcli/SKILL.md

      To activate it globally, run:
        mkdir -p ~/.agents/skills/jira
        ln -sf "#{share}/jcli/SKILL.md" ~/.agents/skills/jira/SKILL.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jcli --version")
  end
end
