#!/usr/bin/env bash
# update-formula.sh — regenerate Formula/jcli.rb for a given release version.
#
# Usage:
#   bash scripts/update-formula.sh <version> <dist-dir> <github-repo>
#
# Example:
#   bash scripts/update-formula.sh v1.2.0 dist steveohara/jcli
#
# The script expects the following tarballs to already exist in <dist-dir>:
#   jcli-<version>-darwin-amd64.tar.gz
#   jcli-<version>-darwin-arm64.tar.gz
#   jcli-<version>-linux-amd64.tar.gz
#   jcli-<version>-linux-arm64.tar.gz

set -euo pipefail

VERSION="${1:?Usage: $0 <version> <dist-dir> <github-repo>}"
DIST_DIR="${2:?Usage: $0 <version> <dist-dir> <github-repo>}"
GITHUB_REPO="${3:?Usage: $0 <version> <dist-dir> <github-repo>}"

BASE_URL="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}"
FORMULA="Formula/jcli.rb"

checksum() {
  local file="$1"
  if command -v sha256sum &>/dev/null; then
    sha256sum "$file" | awk '{print $1}'
  else
    shasum -a 256 "$file" | awk '{print $1}'
  fi
}

echo "Computing checksums from ${DIST_DIR}/ ..."
SHA_DARWIN_AMD64=$(checksum "${DIST_DIR}/jcli-${VERSION}-darwin-amd64.tar.gz")
SHA_DARWIN_ARM64=$(checksum "${DIST_DIR}/jcli-${VERSION}-darwin-arm64.tar.gz")
SHA_LINUX_AMD64=$(checksum  "${DIST_DIR}/jcli-${VERSION}-linux-amd64.tar.gz")
SHA_LINUX_ARM64=$(checksum  "${DIST_DIR}/jcli-${VERSION}-linux-arm64.tar.gz")

mkdir -p Formula

cat > "${FORMULA}" << FORMULA
# This file is generated by scripts/update-formula.sh — do not edit by hand.
# To update: make release VERSION=<version>
class Jcli < Formula
  desc "Comprehensive command-line interface for the Jira REST API v2"
  homepage "https://github.com/${GITHUB_REPO}"
  version "${VERSION#v}"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "${BASE_URL}/jcli-${VERSION}-darwin-amd64.tar.gz"
      sha256 "${SHA_DARWIN_AMD64}"
    end

    on_arm do
      url "${BASE_URL}/jcli-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE_URL}/jcli-${VERSION}-linux-amd64.tar.gz"
      sha256 "${SHA_LINUX_AMD64}"
    end

    on_arm do
      url "${BASE_URL}/jcli-${VERSION}-linux-arm64.tar.gz"
      sha256 "${SHA_LINUX_ARM64}"
    end
  end

  def install
    bin.install "jcli"
    (share/"jcli").install "SKILL.md"
  end

  def caveats
    <<~EOS
      The Jira agent skill for OpenCode and compatible AI tools has been installed to:
        #{share}/jcli/SKILL.md

      To activate it globally, run:
        mkdir -p ~/.agents/skills/jira
        ln -sf "#{share}/jcli/SKILL.md" ~/.agents/skills/jira/SKILL.md
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jcli --version")
  end
end
FORMULA

echo "Updated ${FORMULA} for ${VERSION}"
echo "  darwin/amd64  ${SHA_DARWIN_AMD64}"
echo "  darwin/arm64  ${SHA_DARWIN_ARM64}"
echo "  linux/amd64   ${SHA_LINUX_AMD64}"
echo "  linux/arm64   ${SHA_LINUX_ARM64}"
